@extends('layouts.app')
@section('content')

    <div class="banner-wrap d-none d-md-block" style="position: relative;">
        <div class="banner-faculty"></div>
{{--        <div class="custom-shape-divider-bottom-1663856745">--}}
{{--            <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">--}}
{{--                <path d="M598.97 114.72L0 0 0 120 1200 120 1200 0 598.97 114.72z" class="shape-fill"></path>--}}
{{--            </svg>--}}
{{--        </div>--}}
    </div>

    <div class="bg-red-solid py-5" style="position: relative; height: 100%;">
        <div class="container">
            <div class="mt-3 font-staat text-white text-center" style="font-size: 100px;">faculty</div>
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3">
{{--                <div class="col-sm font-staat text-white d-none d-lg-block" style="font-size: 100px; transform: rotate(-90deg) translate(-50%, -50%); height: 100%;">teachers</div>--}}

                <x-faculty name="lanette-cook" title="owner" bio="has danced competitively since the age of 14 while studying under the instruction of Elise Donnow. She was a member of the Davis Muscial Theatre Company in Davis, California and performed in musicals including The Wizard of Oz, Oliver, and Annie. Lanette was a Senior Lieutenant on the Clear Creek Cavalier Dance team where she danced for 3 years under the direction of Jill Terrell. Upon high school graduation, Lanette received a dance scholarship to the University of Houston and became a member of the Cougar Doll Dance Team. In addition to dancing, she studied architecture and vocal jazz while maintaining membership with two local area Vocal Jazz groups: Bay Creek Jazz Express and the University of Houston Jazz Singers, both under the direction of Dr. Sue Cruse. Lanette has appeared in the Houston Thanksgiving Day Parade and has performed overseas, in England and Wales. Her singing credits include performances at Ovations in Houston and in New Orleans. Her competing dance students have received high marks at competitions and she has received “Best Choreography” awards. In addition to voice and dance, Lanette has a background in piano, guitar, flute and trombone. She enjoys life with her husband, Daniel, and their three wonderful children, Ansleigh, Andrew, and Anderson."/>
                <x-faculty name="katelyn-manriquez" title="company director" bio="began dancing and competing at the age of 7 where it quickly became her passion. Growing up, she trained at Elite Dance Academy and with Steven Boyd Dance Ensemble getting to work with many talented instructors and choreographers. Katelyn has attended many competitions, conventions, and intensives in Texas, Florida, New York, California, Pennsylvania and Arizona where she received numerous high point awards and scholarships. Among these intensives, were the Point Park University and Joffrey Jazz and Contemporary intensives. Katelyn attended The High School for the Performing and Visual Arts (HSPVA) her freshman year of high school and then chose to return to Clear Creek High School where she served as junior lieutenant and 1st senior lieutenant of the Cavaliers. After high school, she attended Texas A&M University where she graduated with a Bachelor of Science in Kinesiology with an emphasis on motor behavior and a minor in dance. While at Texas A&M, Katelyn was a member of the Aggie Dance Team where she had the honor of performing at all home women and men’s basketball games. She also had the chance to travel to numerous states with the basketball teams to perform at both SEC and NCAA tournaments. Along with her passion for dance, she also holds a love for teaching. Katelyn has taught for both Crowd Pleasers Dance, where she traveled across Texas teaching numerous high school drill teams, and for Elite Dance Academy. As an instructor, Katelyn has received numerous choreography and High point awards for her jazz routines. Elite has always been her home, and she looks forward to training the next generation of dancers each day." />
                <x-faculty name="tuesday-moon-boswell" title="assistant director" bio="is from Houston, Texas where she attended San Jacinto College and found her passion for the arts. Tuesday received her Bachelors of Fine Arts in Dance from Sam Houston State University in Huntsville, Texas. During her time at SHSU, she had the opportunity to perform in Bailando Dance Festival in Corpus Christi, Barn Storm Dance Festival in Houston, Contemporary Dance Festival in Boston and Dance Gallery in New York City. Tuesday has guest performed with NobleMotion Dance, in shows such as 'StormFront', 'Supernova', 'Catapult' and, 'Drone' at the Hobby Center of Performing Arts, under the direction of Andy and Dionne Noble. Tuesday has worked with artists such as Jennifer Mabus and Lynn Lane in Transitory Sound and Movement Collective, Jorrell Lawyer-Jefferson in Houston Grand Opera’s production of 'AIDA', Dwain Travis in Juxtapose Arts Collective, Amy Morrow from Theorists and has had the opportunity to collaborated with many other artists throughout Houston. Tuesday has had the opportunity to present her works in Dance Source Houston’s 'Mind The Gap', Denton Dance Festival and at San Jacinto College as a guest choreographer. As an educator and artist, Tuesday is currently Assistant Director at Elite Dance Academy and continues to share her passion and love for the arts." />
                <x-faculty name="molly-michelle" title="dance instructor" bio="has been pursing her dance career for 20 years. She has acquired a Bachelor in Fine Arts: Choreography and Performance, from Texas State. She started teaching when she was 14 years old, which lead her to discover her natural love for not only performing and competing, but choreographing. Molly sees beauty in every aspect of life, whether the situation is good or bad. She allows those emotions to naturally and honestly transfer into her choreography. She has worked for Crowd Pleasers Dance Company, Elite Dance Academy, San Antonio Dance Academy, Central Texas Ballet Conservatory, Soundbox Houston, Starlight Dance Studio, Clear Lake Rockettes and many more. She has choreographed for numerous studios, drill teams, and soloists all over Texas. Most of which were recognized as 'Outstanding Choreography'. Molly has competed her whole life and was named Miss Dance Drill Team Texas 2009. She then went on to compete in Miss USA in Los Angeles. Molly moved to Los Angeles in 2014 to train and further her dance career. She completed the work-study program for Debbie Reynolds Dance Studio. Molly moved back to Houston to share her knowledge and passion with the dance community. She has started her own Company with Holly Austin and Eileen Tayum. Soulceptions Dance Company is the first of its kind in Houston, fusing the two styles of contemporary and hip hop. Molly likes to keep an open mind not only as a teacher, but as a student. She tries to take every class that comes her way. She gets the most joy from dancing by sharing her passion and knowledge with others. She is excited for all of the new opportunities that present themselves and is thankful for everyone that crosses her path. " />
                <x-faculty name="erica-newsom" title="dance instructor" bio="began dancing at the age of only 3. She started competitive dance at the age of 6 where she competed several Lyrical and Tap solos, which is where her passion for dance all began. She went on to become a Santa Fe Tribal Belle her freshman year of High School where she held military officer positions including Line Lieutenant, Major and Colonel her senior year. After graduating from Santa Fe High School in 2010 she attended College of the Mainland and graduated with an Associate of Arts degree. Erica started teaching dance at the age of 14 and has continued to teach dance to this day. She danced professionally as a Houston Rockets Power Dancer for 3 seasons from 2011-2014. While dancing for the Rockets she participated in many public appearances and represented the organization at the 2013 NBA All Star Game.  One highlight of this All Star week was performing as a backup dancer for B.o.B and Ludacris. Erica is the former Owner/Director of Charm’s Dance Studio.  From 2015-2020 her students competed and received numerous awards and accolades.  The studio received the ADCC award in 2018. As an instructor her routines received several awards such as 1st place overalls and numerous judge’s choice awards. She has also received many choreography awards for her tap routines over the years. Erica is experienced in several styles of dance however has always had such a passion for teaching tap. In addition to teaching dance Erica also enjoys teaching adult fitness classes. She has taught dance cardio classes for several years and received her Barre’ certification from ABT in 2022. She truly loves being a part of the Elite Dance Academy staff and cannot wait to share her love of dance. When Erica is not teaching dance she is spending time with her husband, Taylor, and their two children, Stella and Ty." />
                <x-faculty name="ruben-trevino" title="dance instructor" bio="graduated magna cum laude from Sam Houston State University in May 2012 with a bachelor of fine arts in dance performance. While at Sam Houston University, Ruben trained under the direction of Jennifer Pontius, Jonathan Charles, Andy Noble, Dana Nicolay, and Dionne Noble. While in college, Ruben was been chosen and participated to perform at the American college dance festival Association gala selection concert twice with his university. Ruben was on scholarship and danced in numerous faculty concert graduate concert and student concerts. Ruben was also selected and given the opportunity to perform and a guest residency piece that was choreographed by Jane Weiner from Hope stone dance Company.

Since relocating to Houston in 2012, Ruben has been contracted and performed with Karen Stokes Dance, ChinaCat dance, Bayou City Productions, Jonathan Charles, Ashley Horn, FreneticCore, Kingwood Dance Theatre, American Academy of Dance, Sandra Organ Dance Company, Noblemotion dance, and the Pilot Dance Project.

Ruben spent the last five years of his professional career dancing with Uptown Dance Company where he trained under Adrian Ciobanu and Alex Pandiscio. He has had the opportunity to learn choreography and take master classes from highly qualified teachers including Krissy Richmond, Tina bohnatedt, Karina Gonzalez, Rupert Edwards, Chet Walker, Andre Silva, Barry Kerollis, Priscilla Nathan Murphy to name a few. " />
{{--                <x-faculty name="" title="" bio="" />--}}
            </div>

        <div style="height: 300px;"></div>
        <div class="custom-shape-divider-bottom-1648524823" style="transform: translateY(1px);">
            <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
                <path d="M892.25 114.72L0 0 0 120 1200 120 1200 0 892.25 114.72z" class="shape-fill"></path>
            </svg>
        </div>
    </div>
    </div>

@endsection
